# Generated by Django 4.2.1 on 2023-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgpath',
            field=models.TextField(),
        ),
    ]
